### PR TITLE
add mips64 cpu

### PR DESCRIPTION
**Pull request by shanjiantao**
add mips64 cpu constraints value

### CODE REVIEW

**Review by aiuto — COMMENTED** [review]
Let's get back to you next week on this. We are trying to avoid having a select()ion trap of ever more precise versions, that break existing code when a new type is added.

For mips, I think we want to start with mips32 and mips64 at no specified revision levels. If a user need further refinement  we'll support adding a new constraint ("mipscpu" ?) which can disambiguate sub versions. 

What is your (as precise as you can be) expectation of what you think mips64 means.

**Comment by shanjiantao** [comment]
@aiuto 
thanks replay! 

Actually, we have finished compiler bazel from scratch on mips64el and ready to submit PRs to bazel after we can add mips64 constrant value to platform. 

In terms of architecture naming, mips is very similar to x86,  mips32 contains mips32 and mips32el, mips64 contains mips64 and mips64el. It is easy to understand through our adaptation code.

```
diff --git a/src/main/java/com/google/devtools/build/lib/util/CPU.java b/src/main/java/com/google/devtools/build/lib/util/CPU.java
index 075c94a..3d9c24b 100755
--- a/src/main/java/com/google/devtools/build/lib/util/CPU.java
+++ b/src/main/java/com/google/devtools/build/lib/util/CPU.java
@@ -27,6 +27,7 @@ public enum CPU {
   ARM("arm", ImmutableSet.of("arm", "armv7l")),
   AARCH64("aarch64", ImmutableSet.of("aarch64")),
   S390X("s390x", ImmutableSet.of("s390x", "s390")),
+  MIPS64("mips64",ImmutableSet.of("mips64","mips64el")),
   UNKNOWN("unknown", ImmutableSet.<String>of());
```

As far as I know, no one uses mips32 anymore, i can't even find mips32 products, but it is certain that we will maintain mips64.

**Comment by gregestren** [comment]
Thanks for this contribution, @shanjiantao .

I agree with @aiuto that we, as a combined reviewer / contributor community, need to further clarify our expectations of what should and shouldn't go into this repo. With the ultimate goal that it really provides generic, canonical names across projects that maximize interoperability.

We have sketch standards at https://github.com/bazelbuild/platforms#adding-a-canonical-constraint-value. But we need to expand and signal boost it, including new clear examples and counter-examples.

Your particular contribution looks pretty solid to me, especially given your followup explanation. Generally, we want to avoid a future where two targets with *mostly* similar architectures have totally incompatible `select`s because the conditions are so fine-grained.

**Comment by shanjiantao** [comment]
@gregestren 
All right, i think i hava understood what you mean. Ensuring clarity and simplicity of constraints is essential to the development of Bazel, so the plan to add a new architecture is very import. 

As for the mips i have explained, i hope you guys can contact me again after you have  a suitable plan, because it is really important for our followup work, thanks!

**Comment by gregestren** [comment]
We chatted some more and are happy to approve this specific request. Thanks for your further input and patience.

**Review by gregestren — APPROVED** [review]

**Comment by shanjiantao** [comment]
Hi @gregestren, thank you for your effort.

@aiuto It looks like you need your help to merge. Thank you!

**Comment by shanjiantao** [comment]
Hi @gregestren, thank you for you efforts.

@aiuto  It looks like you need your help to merge. Thanks!

**Review by aiuto — APPROVED** [review]

**Comment by aiuto** [comment]
Whump, whump.   The cla bot seems wedged up.

**Comment by aiuto** [comment]
Oh. Now I see. The auto-import did something and unblocked.
I strongly believe we should NOT auto-import this into Google. It should be a manual copybara run to pull from github when we want to sync.

**Pull request merged**
