### PR TITLE
os: add WASI (WebAssembly System Interface).

### PR DESCRIPTION
**Pull request by PiotrSikora**
Signed-off-by: Piotr Sikora <piotrsikora@google.com>

### CODE REVIEW

**Comment by katre** [comment]
How would this be used? I assume this is for wasm code, to build code that runs in a browser? So the target platform would has the new `:wasi` constraint present?

**Comment by PiotrSikora** [comment]
@katre WASI is specifically designed for non-browser use cases of WebAssembly, but yeah, this is for the platform constraints. Right now, we have to carry it in rules_rust (https://github.com/bazelbuild/rules_rust/pull/477) to differentiate between `wasm32-unknown-unknown` and `wasm32-wasi` targets. Note that WASI is becoming de-facto standard, and languages other than Rust are also compiling for this target (e.g. Emscripten with `STANDALONE_WASM=1`).

**Comment by katre** [comment]
Thanks for the clarification!

**Comment by katre** [comment]
Are there any documentation about WASI (ideally non-rust-specific) which you could include in a comment with the new constraint?

**Comment by PiotrSikora** [comment]
> Are there any documentation about WASI (ideally non-rust-specific) which you could include in a comment with the new constraint?

This is probably the best overview, but I'm not sure how persistent this link is going to be:
https://github.com/bytecodealliance/wasmtime/blob/main/docs/WASI-overview.md

Do you want me to add it?

**Comment by katre** [comment]
Yes please, I think that will help explain the purpose.

**Comment by PiotrSikora** [comment]
Done. Thanks!

**Review by katre — APPROVED** [review]

**Pull request merged**
