### PR TITLE
add loongarch64 cpu

### PR DESCRIPTION
**Pull request by zunley**
This PR depends by https://github.com/bazelbuild/bazel/pull/23965

### CODE REVIEW

**Comment by katre** [comment]
Can you give some details? What is loongarch64? Is it going to be referenced by many different bazel users? Would this work if you defined it locally for your own project?

We don't want this repo to be a list of every CPU architecture, just ones that appear in common for many different projects.

**Review by abner-chenc — APPROVED** [review]

**Comment by zunley** [comment]
> Can you give some details? What is loongarch64? 

LoongArch64 is a RISC-style architecture, Like riscv64, it has been supported by many upstream such as [kernel](https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/arch/loongarch), [gcc](https://gcc.gnu.org/git/?p=gcc.git;a=tree;f=gcc/config/loongarch;h=76e63abfb4558e9de7538a95717de4f42f0f0614;hb=HEAD), [golang](https://go.dev/doc/go1.19#loong64), [openjdk](https://github.com/openjdk/jdk/blob/master/src/hotspot/os/linux/os_linux.cpp#L1777), [rust](https://github.com/rust-lang/compiler-team/issues/518), etc.

More importantly, [Debian](https://wiki.debian.org/Ports/loong64) and [Alpine] (https://wiki.alpinelinux.org/wiki/Loongarch64) are supporting loongarch64, and bazel is a very important package in them.

> We don't want this repo to be a list of every CPU architecture, just ones that appear in common for many different projects.

As mentioned before, loongarch64 is not `one of every CPU architecture`, but a widely used CPU architecture.

By the way, LoongArch64 is the 64-bit version of [LoongArch](https://wiki.debian.org/LoongArch), loong64 is an alias for loongarch64, just like arm64 and aarch64.

**Comment by katre** [comment]
There is no need for this to be added to the `@platforms` repo. Define this locally in your project (where you define your own custom platforms and toolchains).

**Comment by zunley** [comment]
@katre Bazel will download the official platform file when building, which is difficult for users using debian-loongarch64.

**Pull request closed without merging**
