### PR TITLE
add wasm cpu

### PR DESCRIPTION
**Pull request by lizan**
Signed-off-by: Lizan Zhou <lizan@tetrate.io>

### CODE REVIEW

**Comment by katre** [comment]
Is wasm a CPU architecture? How is it intended to be used?

**Comment by gregestren** [comment]
@lizan can you speak more to the concerns expressed in https://github.com/bazelbuild/platforms#adding-a-canonical-constraint-value?

I realize we still need to evolve the process. It's not immediately obvious what belongs in this repo vs. not, and we need clearer agreement on how to even have the right discussions to figure that out. 

But the link above is at least a starting point. This is important not just for us (reviewers and PR producer), but anyone else who may ever look at or consider using these.

**Comment by lizan** [comment]
@katre yes it should be treated as a CPU architecture. Go/Rust and LLVM treat it as an arch.

@gregestren Sure, the `wasm32` already defined in [rules_rust](https://github.com/bazelbuild/rules_rust/blob/fe9a91e8b42f731aeb3b596246f6bf4bb9a88dc3/rust/platform/platform.bzl#L83), 64bit is a future feature so if we don't like, I can remove that. I am working on make this build in [proxy-wasm](https://github.com/proxy-wasm/proxy-wasm-cpp-sdk) and [Envoy WASM](https://github.com/envoyproxy/envoy-wasm) integration, this uses cpu value `wasm`. The bazel [C++ Toolchain blog](https://docs.bazel.build/versions/master/tutorial/cc-toolchain-config.html) uses `asmjs` which is quite confusing as well. There should be a canonical constraint settings for this instead of having CPU value defined everywhere.

**Comment by lizan** [comment]
gently ping?

**Comment by katre** [comment]
Looking today, sorry again for the delays.

**Comment by katre** [comment]
Working to merge this now!

**Pull request merged**
