### PR TITLE
Add cpu value riscv64

### PR DESCRIPTION
**Pull request by meteorcloudy**

### CODE REVIEW

**Comment by katre** [comment]
@meteorcloudy: Can you provide some context on why this is needed?

**Comment by meteorcloudy** [comment]
I'm upstreaming a patch we made in the Debian package to make Bazel build on RISCV64
See https://github.com/bazelbuild/bazel/pull/13057

**Comment by meteorcloudy** [comment]
@katre Can we get this merged?

**Comment by katre** [comment]
Yes, I'll take it back over and get to it today.

**Comment by meteorcloudy** [comment]
Thanks! Can we have a new release to include this change?

**Comment by katre** [comment]
Release created, see https://github.com/bazelbuild/bazel/pull/13118 to use it in Bazel.

**Pull request merged**
