### PR TITLE
Add QNX as a possible constraint value

### PR DESCRIPTION
**Pull request by narendasan**
Have been using bazel to compile for QNX, would like to see it as a constraint value.

### CODE REVIEW

**Comment by gregestren** [comment]
Have you had need to use a specific `constraint_value` for this?

**Comment by narendasan** [comment]
Currently for my project I am using ccToolchainConfig's for both QNX and Linux (for aarch64). The issue was that build artifacts would clobber each other because of the shared CPU arch. I was hoping the new platforms feature might help. Considering QNX is a reasonably common OS I thought it might be worth including it in the canonical set of platforms.

**Comment by gregestren** [comment]
The idea absolutely sounds fair!

Since we want to be careful not to explode the set of values too easily (i.e. once they're added we can't easily roll them back), can you prototype the expected fix and verify this solves the problem for you? If so I think that's a concrete call for adding this.

**Comment by narendasan** [comment]
Sounds good, will update when I have something that works.

**Comment by katre** [comment]
Merged as 19815c270457359ba79d6c6a57e73ee4288692f5.

**Pull request closed without merging**
